"""added index to book params

Revision ID: 60592246419e
Revises: d6b92fbe0947
Create Date: 2024-08-15 00:43:15.711239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60592246419e'
down_revision: Union[str, None] = 'd6b92fbe0947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_isbn_key', 'books', type_='unique')
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_created_by'), 'books', ['created_by'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_index(op.f('ix_books_name'), 'books', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_name'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_created_by'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.create_unique_constraint('books_isbn_key', 'books', ['isbn'])
    # ### end Alembic commands ###
